### ISSUE TITLE
Wormworx app is not compatible with Samsung Galaxy S5 with Android 6.0.1

### ISSUE THREAD

**Issue by clausagerskov** [portegys/WormSim#1]
When looking up the wormworx app on the google play store the google store says "your device isn't compatible with this version"
![screenshot_20171017-000638](https://user-images.githubusercontent.com/13769591/31637459-21a241ee-b2cf-11e7-9e5c-5ba664b87c96.png)

**Comment by portegys** [comment]
Thanks for getting this on record. Will look into it after getting ahead of a couple of things.

**Comment by portegys** [comment]
Unfortunately it looks like the Google Play Store excluded the Galaxy S5 and I can't change it:
![image](https://user-images.githubusercontent.com/768944/31703193-62c7db86-b390-11e7-99b7-b4b43c47f28b.png)
![image](https://user-images.githubusercontent.com/768944/31703214-7f79eee0-b390-11e7-9cc2-c59ad245884e.png)
